
### GET todos los restaurants
GET http://localhost:3000/restaurants

### GET para todas las reviews
GET http://localhost:3000/reviews

### Crear un nuevo restaurant
POST http://localhost:3000/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5Njk2ODAxNiwiZXhwIjoxNjk2OTcxNjE2fQ.-Lb1GanRubQPC0oMkldyQPpv52B3jP7K9jJ77w_ilPI

{
  "name": "Tostadas de la abuela",
  "location": "Calle 123",
  "image": "https://eu-assets.simpleview-europe.com/lillehammer/imageresizer/?image=%2Fdmsimgs%2FRestauranten_2_52519962.jpg&action=ProductDetail2020"
}

### PATCH para actualizar imagen de restaurant
PATCH http://localhost:3000/restaurants/1d31575e62d111eea7bf47961cc8979b/image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5NzA0MjA4NiwiZXhwIjoxNjk3MDQ1Njg2fQ.oYnCOPRGjd8NgkcNBGw5QlKyQEZ-obQXQ1d9sV2W2tU

{
  "image": "https://www.cadena3.com/admin/playerswf/fotos/ARCHI_8893341200x771.jpg"
}

### GET restaurant por ID
GET http://localhost:3000/restaurants/1d315254-62d1-11ee-a7bf-47961cc8979b

### POST nuevo usuario
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "flerkenito",
  "password": "flerkenito",
  "email": "flerkenito@example.com"
}

### POST para login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "flerkeno",
  "password": "flerkeno"
}

### DELETE para borrar un usuario
DELETE http://localhost:3000/user/16
Content-Type: application/json

### DELETE para borrar un restaurant
DELETE http://localhost:3000/restaurants/8ffc24bbdb3e4e4e8be7c7338912c787
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5Njk2ODAxNiwiZXhwIjoxNjk2OTcxNjE2fQ.-Lb1GanRubQPC0oMkldyQPpv52B3jP7K9jJ77w_ilPI

### GET para traer todos los reviews
GET http://localhost:3000/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5NjQ1MDcwNywiZXhwIjoxNjk2NDU0MzA3fQ.iyfg6SNUMNpst2NXchoLcNcNbOamgLtBHr7OBo8rpSE

### GET usuario por ID
GET http://localhost:3000/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5NjQ1NzE4MywiZXhwIjoxNjk2NDYwNzgzfQ.zwevhZQDKLX62mrZpX4wIWHoz6HsCZVFUF4iVv68r8I

### Crear una nueva reseña
POST http://localhost:3000/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5NjQ1NzE4MywiZXhwIjoxNjk2NDYwNzgzfQ.zwevhZQDKLX62mrZpX4wIWHoz6HsCZVFUF4iVv68r8I

{
  "userId": 1,
  "restaurantId": "1d31575e-62d1-11ee-a7bf-47961cc8979b",
  "rating": 4,
  "comment": "Muy buen lugar"
}

### Actualizar
PATCH http://localhost:3000/reviews/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5Njg4MjI3MSwiZXhwIjoxNjk2ODg1ODcxfQ.j_BJp9mOKD4_Hilcq1otF94cjZAHIYKJgez2hoEAft0

{
  "rating": 5,
  "comment": "Muy buen lugar"
}

### Actualizar avatar de usuario
PATCH http://localhost:3000/user/2/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5NzEyMjE2NCwiZXhwIjoxNjk3MTI1NzY0fQ.bkb6rkHqS0174tw-KKl4g3MNbwfE5z2ijB8g8ZI46ys

{
  "avatarUrl": "http://localhost:3000/avatars/tosta.jpeg"
}


### DELETE para eliminar una review

DELETE http://localhost:3000/reviews/58
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5NzA0MjA4NiwiZXhwIjoxNjk3MDQ1Njg2fQ.oYnCOPRGjd8NgkcNBGw5QlKyQEZ-obQXQ1d9sV2W2tU
